### ISSUE TITLE
next font error when run yarn dev

### ISSUE THREAD

**Issue by zjrwtx** [miurla/morphic#16]
![image](https://github.com/miurla/morphic/assets/86822589/0cee56dc-284d-4793-959a-3bc7bb747351)
![image](https://github.com/miurla/morphic/assets/86822589/ef5ab0ef-7a31-426d-bbb6-6af9229f712f)

**Comment by Evilander** [comment]
I get the same error using bun.

**Comment by cnericxu** [comment]
Windows  11, I got the same error

**Comment by aaronpeng2020** [comment]
update nodejs to latest, i fixed thit error ,but get more other..

**Comment by aaronpeng2020** [comment]
npm install next@latest

**Comment by cnericxu** [comment]
yep, thanks. I gave up it on Windows(I was at office),  now it's perfect on Mac(I have a m2 pro at home)

for developers who use Windows, just wait. It's not working on Windows yet right now.

**Comment by zjrwtx** [comment]
> update nodejs to latest, i fixed thit error ,but get more other..
hey guys
Node.js v20.11.1 and npm install next@latest still appear the same error

**Comment by miurla** [comment]
There seems to have been an issue with Next.js 14.2.0 on Windows:
https://github.com/vercel/next.js/issues/64371

It has been reported that the issue is resolved in Next.js 14.2.1
I have deployed a version with the latest Next.js installed, so please try again with the latest code.
https://github.com/miurla/morphic/pull/47
